// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArv9KYzT3MKQK1VOayvqZmVpZvziiaEBs',
    appId: '1:1085973434586:web:0cb47be71f0bbb54',
    messagingSenderId: '1085973434586',
    projectId: 'fb111-bc461',
    authDomain: 'fb111-bc461.firebaseapp.com',
    databaseURL: 'https://fb111-bc461.firebaseio.com',
    storageBucket: 'fb111-bc461.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXvG9rtm19juXQRhr1uSoCSlrS1RsMYGE',
    appId: '1:1085973434586:android:6720950c137d8a921dd5e3',
    messagingSenderId: '1085973434586',
    projectId: 'fb111-bc461',
    databaseURL: 'https://fb111-bc461.firebaseio.com',
    storageBucket: 'fb111-bc461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB82S1mp2Mm5Dclb2iHmdLrDM9rmAEutnU',
    appId: '1:1085973434586:ios:1015efa04d46c1f81dd5e3',
    messagingSenderId: '1085973434586',
    projectId: 'fb111-bc461',
    databaseURL: 'https://fb111-bc461.firebaseio.com',
    storageBucket: 'fb111-bc461.appspot.com',
    androidClientId:
        '1085973434586-9slp6nfolgba9qvv5noj7u9oovi9t4ql.apps.googleusercontent.com',
    iosClientId:
        '1085973434586-nh7i7bqg2lk02iopfvrlf4k58rna6q3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.moovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB82S1mp2Mm5Dclb2iHmdLrDM9rmAEutnU',
    appId: '1:1085973434586:ios:1015efa04d46c1f81dd5e3',
    messagingSenderId: '1085973434586',
    projectId: 'fb111-bc461',
    databaseURL: 'https://fb111-bc461.firebaseio.com',
    storageBucket: 'fb111-bc461.appspot.com',
    androidClientId:
        '1085973434586-9slp6nfolgba9qvv5noj7u9oovi9t4ql.apps.googleusercontent.com',
    iosClientId:
        '1085973434586-nh7i7bqg2lk02iopfvrlf4k58rna6q3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.moovies',
  );
}
